### ISSUE TITLE
Refatoração de tipo de unidade

### ISSUE THREAD

**Issue by RyanOxon** [TreinaDev/condominions#46]
- [x] Configurar autorização para o administrador
- [x] Refatorar para ser aninhado com o condomínio
- [x] Estilizar os formulários
- [x] Refatorar nome do método `p_metrage` para ser mais legível com a função dele
- [x] Padronizar flash messages no `controller` do condomínio
- [x] Adicionar o campo fração ideal ao formulário

**Comment by akaninja** [comment]
Acho que já foi falado que as tarefas não devem ser apenas listas, mas devem conter uma descrição clara e concisa da funcionalidade e motivação.
